name: 书旗小说
on:
  workflow_dispatch:
  schedule:
     - cron: '1 */1 * * *'
  watch:
    types: started
  repository_dispatch:
    types: shuqi
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: 
          git clone https://github.com/Lxg2/Scripts.git ~/Scripts
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          cd ~/Scripts
          npm install
      - name: '运行 【书旗小说&极速版】'
        run: |
          cd ~/Scripts
          node Task/shuqi.js
