name: 微客众智

on:
  workflow_dispatch:
  schedule:
     - cron: '10 */1 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
         WKZZ_HD: ${{ secrets.WKZZ_HD }}
         TZ: Asia/shanghai
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/heeroyuy7/heeroyuy7.git ~/heeroyuy7
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/heeroyuy7
          npm install
      - name: '运行 【微客众智】'     
        run: |
          cd ~/heeroyuy7
          node Task/wkzz.js
